<div class="container">
    <div class="item title">
        <h2>新参者</h2>
        <h2>New Arrival</h2>
    </div>
    <div class="item etalase">
        <img src='<?php echo $this->getViewFileUrl('Moonlay_CustomHome::images/mcollection.jpg'); ?>' />
        <div class="collection">
            <a href="#">メンズコレクション</a>
            <br />
            <a href="#">Men’s Collection</a>
        </div>
    </div>
    <div class="item etalase">
        <img src='<?php echo $this->getViewFileUrl('Moonlay_CustomHome::images/wcollection.jpg'); ?>' />
        <div class="collection">
            <a href="#">女性のコレクション</a>
            <br />
            <a href="#">Women’s Collection</a>
        </div>
    </div>
</div>
